"""initial schema: users, inspections, products, images, ocr, fields, rules, assessments, findings, measurements, reports, audit

Revision ID: 3082113b7b58
Revises: 
Create Date: 2026-09-05 12:32:47.080844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3082113b7b58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=80), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.String(length=20), nullable=True),
    sa.Column('effective_to', sa.String(length=20), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('applicability', sa.JSON(), nullable=True),
    sa.Column('condition', sa.String(length=1000), nullable=True),
    sa.Column('verify_prompt', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('package_structure', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('special_status', sa.String(length=40), nullable=True),
    sa.Column('product_name_hint', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ruleset_version', sa.String(length=40), nullable=True),
    sa.Column('process_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_category'), 'inspections', ['category'], unique=False)
    op.create_index(op.f('ix_inspections_public_id'), 'inspections', ['public_id'], unique=True)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=30), nullable=False),
    sa.Column('ruleset_version', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_inspection_id'), 'assessments', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_assessments_rule_id'), 'assessments', ['rule_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('raw', sa.String(length=500), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('source_ocr_ids', sa.JSON(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_inspection_id'), 'extracted_fields', ['inspection_id'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('processed_url', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('quality_score_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_images_inspection_id'), 'inspection_images', ['inspection_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_inspection_id'), 'reports', ['inspection_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_field_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_blocks_image_id'), 'ocr_blocks', ['image_id'], unique=False)
    op.create_index(op.f('ix_ocr_blocks_inspection_id'), 'ocr_blocks', ['inspection_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('ocr_block_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=30), nullable=False),
    sa.Column('ruleset_version', sa.String(length=40), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('automated_result', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['inspection_images.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['ocr_block_id'], ['ocr_blocks.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_assessment_id'), 'findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_findings_image_id'), 'findings', ['image_id'], unique=False)
    op.create_index(op.f('ix_findings_inspection_id'), 'findings', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_inspection_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_image_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_assessment_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_ocr_blocks_inspection_id'), table_name='ocr_blocks')
    op.drop_index(op.f('ix_ocr_blocks_image_id'), table_name='ocr_blocks')
    op.drop_table('ocr_blocks')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_reports_inspection_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_inspection_images_inspection_id'), table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_extracted_fields_inspection_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_assessments_rule_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_inspection_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_public_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_category'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
